apiVersion: hog.immortal.hedgehogs/v1
kind: HogEye
metadata:
  name: the-eye
  namespace: hog
spec:
  appTokenSecret: "hogeye-secrets"
  slackChannels: "U051DPPFNNT"
  queryNamespace: hog
  queryTime: "59 13 * * *"
  ageThreshold: 0
