---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hog-immortal-hedgehogs-v1-hogeye
  failurePolicy: Fail
  name: mhogeye.kb.io
  rules:
  - apiGroups:
    - hog.immortal.hedgehogs
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hogeyes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hog-immortal-hedgehogs-v1-hogeye
  failurePolicy: Fail
  name: vhogeye.kb.io
  rules:
  - apiGroups:
    - hog.immortal.hedgehogs
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hogeyes
  sideEffects: None
