---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hog.immortal.hedgehogs
  resources:
  - hogeyes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hog.immortal.hedgehogs
  resources:
  - hogeyes/finalizers
  verbs:
  - update
- apiGroups:
  - hog.immortal.hedgehogs
  resources:
  - hogeyes/status
  verbs:
  - get
  - patch
  - update
